language: generic
sudo: required

services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - ENVOY_BUILD_SHA=fc747b3c2fd49b1260484572071fe4194cd6824d
  - secure: "XtHUvf9SXDxNS5q0KgW1ueICULoR9WNkFlJuLQez8InwmFcEInXfm+cWAScCZMbnGmbIDvrMK1nZvIK+/RWvv7C0qlwqn9hMJkTNsowl88YLsnI7baYE8OBoDqgufEpiL0SsYhg2xK+SQ7JaKcDR/2qHFJWzh+5xWept9eQziufvf6kKyPQBAeo0oYaaWkw6QhYPNxk2DeJGnrFAu8vOo/PVs59kNtrSNmxhdDkUdRtHG4XF6iw/5Pkbvldzaz2w8H+LcsZCF6fGbAg/rVrcBMWB8wQQnhHU5S/TK9A4w8tUWMj6X5MhurpD15Q3BNYjoqS/M7kI8AuqnjEf/5rG+gPzNuZHPOgsQUzwWhVg1l+jBVz+jlj++UV470vZNpLVHLmlIkEnK+uwHRFQ6mn3ucBArbCJQVELcYx0RAEa8CoA5JF94nRx+csg2714vfrMlRH89GnGSzd/PmXdBirnboAsKQx0U1aXBe985rv5FQj5xYRqwFNbj3gdtSHkd8uW3g7F2KDPLiKbHtD4IqA7K656+dKFrj6JZtLhvznudjhRG+dhmXdZDs3KEkk35ouioPssZkNWo0zWiZY6JxW9cGKairRWrL7xIA7O03cwUc78sAqEPQ4IbeHb6bbMzurIURE9J/2CKTrQeK8Yevy2/ya+/0H4rJpZDyXE6uKxBbs="

script:
- sh travis-build.sh
