language: generic
sudo: required

services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - ENVOY_BUILD_SHA=fc747b3c2fd49b1260484572071fe4194cd6824d
  - secure: pICW+jNQnKfTIi3cupJAzLe4If6FqvJ6OgAQIxfmnTxo/7w6EwzBh8zNqTJ60WCGXc/dqYpOtAYGZ/65hRR9HS9l3/8/wmZGeARoz/IR3dEbMpSQKRWTiF+J6UX24H2ol9u6vGa+JLgQuqJeTDdzGqk6h5sZ6H2a2dedOJ9Ns/QQlN/eCsxvYLHQmdzXtc+vlTAFfL902Y2AW7Ue0lqGdJlnzM9WxxX5amBxf9t73aY+pW4mqeysGPZfSlRdpkVAJd3TzYlC4fdJWYR5DGsHDXnXlQdQ7OcLC9Vpb4f5AAu4XPbdxpxW2oA4hxlV6ya1N+oDlZZo1RZiRugn7ecY7W3a6wI7HI91GbWLJe2BaCRW1TminmGZ+tSErz1AmGiOpiqjKeM7KvMwt2Kv5YpWkZcFy5ac0wSMP1qf9V6Kyn9INiohPCHiiy3vzy5a75fAdIVl9C/5x2n6SmNFf0bCO0RVDqqMBQvScjnAZDFZTKHhXDh8zHdQbhxTg0edKbJ+JimuzJYjvGLZkBVuQtW8XO/3kzycTsgzP8OgLH2Ww7qIP0jZpL4HAqIF5FePZ46u32iYqTmv2CokveMJJoCRK/tNKhB4a3Uc8wIHPPVAiTIme8LGJqDrpdzEKbRF7K3fB+qn2nypGfsdxXquNoNxs4/flBYfEt4sUWysvIpEtdY=

script:
- sh travis-build.sh
